### ISSUE TITLE
Error when put an order when not accepted terms

### ISSUE THREAD

**Issue by victorauren** [Billmate/opencart#125]
When I place the order and have not checked to box, Accept terms it correctly display that you have to accept the terms before putting order. So here the error occurs. Even if I click the box, the button that says "Put order" is faded and says loading. And you can't click. 

![kassa](https://cloud.githubusercontent.com/assets/14887835/13176150/1cc06f44-d710-11e5-9f1f-984cba6d9c11.png)

**Comment by Boxedsolutions** [comment]
Hmm. This has nothing to do with our plugins :( Must be a Opencart bug.

**Comment by Boxedsolutions** [comment]
https://github.com/opencart/opencart/issues/3967 
Please look at this thread.

**Comment by Boxedsolutions** [comment]
Should be fixed in Opencart 2.1.0.2

**Comment by Boxedsolutions** [comment]
Think we could close this @victorauren

**Comment by victorauren** [comment]
Works fine in 1.5.x
Still don't work with the latest OC version

**Comment by Boxedsolutions** [comment]
This has nothing to do with us. Its a opencart issue.

**Comment by victorauren** [comment]
ok, we close this issue then?

**Comment by Boxedsolutions** [comment]
Yes we cant solve it. It should been solved in OC 2.2
