### ISSUE TITLE
I put an order with bank and card and got redirected to a page that says 00

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#55]
![opencart-redirect-bank](https://cloud.githubusercontent.com/assets/10434920/9377645/4db4ba72-471b-11e5-967e-8b506bc0df7a.png)

**Comment by Boxedsolutions** [comment]
This should be fixed now

**Comment by joakim-combain** [comment]
In 2.0 there is still an issue. I'm getting an internal server error after I've been redirected back to the store.

![opencart-fatal-error-accept-url](https://cloud.githubusercontent.com/assets/10434920/9379493/0247b7f6-472a-11e5-9cc6-d7831273c154.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now. Tested the card payment method

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
