### ISSUE TITLE
Min/max value setting doesn't work for invoice and part pay

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#61]

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by joakim-combain** [comment]
There seems to be some issues still.

If I put invoice to have maximum total 500 and my order is 1270, the invoice option is still active.

If I put part pay to have maximum total 500 and my order is 1270, I'm getting this error message:

![opencart partpay minimum error message](https://cloud.githubusercontent.com/assets/10434920/9487663/1ab96b64-4bd4-11e5-95b6-a281158cb441.png)

**Comment by joakim-combain** [comment]
It seems like the issue is that min and max both look for the minimum total. That's why Invoice is showing even though I put 500 as max.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
There is still an issue with going over the max level, I'm getting that error message still.

**Comment by Boxedsolutions** [comment]
Think i Solved it now.

**Comment by joakim-combain** [comment]
This is fixed. Closing it.
